// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssetComposition = `-- name: GetAssetComposition :many
SELECT
    asset_type,
    SUM(balance)::BIGINT as total
FROM kanjo.daily_assets
WHERE date = (SELECT MAX(date) FROM kanjo.daily_assets)
GROUP BY asset_type
ORDER BY total DESC
`

type GetAssetCompositionRow struct {
	AssetType string `json:"asset_type"`
	Total     int64  `json:"total"`
}

func (q *Queries) GetAssetComposition(ctx context.Context) ([]GetAssetCompositionRow, error) {
	rows, err := q.db.Query(ctx, getAssetComposition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssetCompositionRow{}
	for rows.Next() {
		var i GetAssetCompositionRow
		if err := rows.Scan(&i.AssetType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetTrend = `-- name: GetAssetTrend :many
SELECT
    date,
    asset_type,
    SUM(balance)::BIGINT as total
FROM kanjo.daily_assets
WHERE date >= $1
GROUP BY date, asset_type
ORDER BY date, asset_type
`

type GetAssetTrendRow struct {
	Date      pgtype.Date `json:"date"`
	AssetType string      `json:"asset_type"`
	Total     int64       `json:"total"`
}

func (q *Queries) GetAssetTrend(ctx context.Context, date pgtype.Date) ([]GetAssetTrendRow, error) {
	rows, err := q.db.Query(ctx, getAssetTrend, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssetTrendRow{}
	for rows.Next() {
		var i GetAssetTrendRow
		if err := rows.Scan(&i.Date, &i.AssetType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashFlow = `-- name: GetCashFlow :many
SELECT
    DATE_TRUNC('month', date)::DATE as month,
    SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END)::BIGINT as income,
    ABS(SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END))::BIGINT as expenses
FROM kanjo.transactions
WHERE
    date >= $1
    AND date <= $2
    AND is_transfer = FALSE
GROUP BY DATE_TRUNC('month', date)
ORDER BY month
`

type GetCashFlowParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetCashFlowRow struct {
	Month    pgtype.Date `json:"month"`
	Income   int64       `json:"income"`
	Expenses int64       `json:"expenses"`
}

func (q *Queries) GetCashFlow(ctx context.Context, arg GetCashFlowParams) ([]GetCashFlowRow, error) {
	rows, err := q.db.Query(ctx, getCashFlow, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCashFlowRow{}
	for rows.Next() {
		var i GetCashFlowRow
		if err := rows.Scan(&i.Month, &i.Income, &i.Expenses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryBudgets = `-- name: GetCategoryBudgets :many
SELECT
    bc.category_name,
    bc.monthly_budget,
    bc.rollover_enabled,
    bc.color,
    COALESCE(bp.rollover, 0) as rollover,
    COALESCE((
        SELECT ABS(SUM(t.amount))
        FROM kanjo.transactions t
        LEFT JOIN kanjo.categories c ON t.category_id = c.id
        WHERE
            c.display_name = bc.category_name
            AND t.date >= DATE_TRUNC('month', CURRENT_DATE)
            AND t.date < DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month'
            AND t.amount < 0
            AND t.is_transfer = FALSE
    ), 0)::BIGINT as spent
FROM kanjo.budget_categories bc
LEFT JOIN kanjo.budget_periods bp ON
    bc.category_name = bp.category_name
    AND bp.period = DATE_TRUNC('month', CURRENT_DATE)::DATE
ORDER BY bc.category_name
`

type GetCategoryBudgetsRow struct {
	CategoryName    string `json:"category_name"`
	MonthlyBudget   int64  `json:"monthly_budget"`
	RolloverEnabled bool   `json:"rollover_enabled"`
	Color           string `json:"color"`
	Rollover        int64  `json:"rollover"`
	Spent           int64  `json:"spent"`
}

func (q *Queries) GetCategoryBudgets(ctx context.Context) ([]GetCategoryBudgetsRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryBudgetsRow{}
	for rows.Next() {
		var i GetCategoryBudgetsRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.MonthlyBudget,
			&i.RolloverEnabled,
			&i.Color,
			&i.Rollover,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyRankings = `-- name: GetDailyRankings :many
SELECT
    a.institution_name,
    a.account_name,
    a.asset_type,
    a.balance as current_balance,
    COALESCE(p.balance, a.balance) as previous_balance,
    (a.balance - COALESCE(p.balance, a.balance))::BIGINT as change
FROM kanjo.daily_assets a
LEFT JOIN kanjo.daily_assets p ON
    a.institution_name = p.institution_name
    AND a.account_name = p.account_name
    AND a.asset_type = p.asset_type
    AND p.date = (SELECT MAX(date) FROM kanjo.daily_assets WHERE date < (SELECT MAX(date) FROM kanjo.daily_assets))
WHERE a.date = (SELECT MAX(date) FROM kanjo.daily_assets)
ORDER BY ABS(a.balance - COALESCE(p.balance, a.balance)) DESC
LIMIT $1
`

type GetDailyRankingsRow struct {
	InstitutionName string `json:"institution_name"`
	AccountName     string `json:"account_name"`
	AssetType       string `json:"asset_type"`
	CurrentBalance  int64  `json:"current_balance"`
	PreviousBalance int64  `json:"previous_balance"`
	Change          int64  `json:"change"`
}

func (q *Queries) GetDailyRankings(ctx context.Context, limit int32) ([]GetDailyRankingsRow, error) {
	rows, err := q.db.Query(ctx, getDailyRankings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyRankingsRow{}
	for rows.Next() {
		var i GetDailyRankingsRow
		if err := rows.Scan(
			&i.InstitutionName,
			&i.AccountName,
			&i.AssetType,
			&i.CurrentBalance,
			&i.PreviousBalance,
			&i.Change,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySummary = `-- name: GetMonthlySummary :one
SELECT
    COALESCE(SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END), 0)::BIGINT as income,
    COALESCE(ABS(SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END)), 0)::BIGINT as expenses,
    COALESCE(SUM(amount), 0)::BIGINT as net
FROM kanjo.transactions
WHERE
    date >= DATE_TRUNC('month', CURRENT_DATE)
    AND date < DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month'
    AND is_transfer = FALSE
`

type GetMonthlySummaryRow struct {
	Income   int64 `json:"income"`
	Expenses int64 `json:"expenses"`
	Net      int64 `json:"net"`
}

func (q *Queries) GetMonthlySummary(ctx context.Context) (GetMonthlySummaryRow, error) {
	row := q.db.QueryRow(ctx, getMonthlySummary)
	var i GetMonthlySummaryRow
	err := row.Scan(&i.Income, &i.Expenses, &i.Net)
	return i, err
}

const getNetWorth = `-- name: GetNetWorth :one
SELECT COALESCE(SUM(balance), 0)::BIGINT as total
FROM kanjo.daily_assets
WHERE date = (SELECT MAX(date) FROM kanjo.daily_assets)
`

func (q *Queries) GetNetWorth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getNetWorth)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getNetWorthHistory = `-- name: GetNetWorthHistory :many
SELECT
    date,
    SUM(balance)::BIGINT as total
FROM kanjo.daily_assets
WHERE date >= $1
GROUP BY date
ORDER BY date
`

type GetNetWorthHistoryRow struct {
	Date  pgtype.Date `json:"date"`
	Total int64       `json:"total"`
}

func (q *Queries) GetNetWorthHistory(ctx context.Context, date pgtype.Date) ([]GetNetWorthHistoryRow, error) {
	rows, err := q.db.Query(ctx, getNetWorthHistory, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNetWorthHistoryRow{}
	for rows.Next() {
		var i GetNetWorthHistoryRow
		if err := rows.Scan(&i.Date, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpendingPace = `-- name: GetSpendingPace :many
SELECT
    EXTRACT(DAY FROM date)::INTEGER as day_of_month,
    SUM(ABS(amount))::BIGINT as cumulative_spending
FROM kanjo.transactions
WHERE
    date >= DATE_TRUNC('month', CURRENT_DATE)
    AND date <= CURRENT_DATE
    AND amount < 0
    AND is_transfer = FALSE
GROUP BY EXTRACT(DAY FROM date)
ORDER BY day_of_month
`

type GetSpendingPaceRow struct {
	DayOfMonth         int32 `json:"day_of_month"`
	CumulativeSpending int64 `json:"cumulative_spending"`
}

func (q *Queries) GetSpendingPace(ctx context.Context) ([]GetSpendingPaceRow, error) {
	rows, err := q.db.Query(ctx, getSpendingPace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpendingPaceRow{}
	for rows.Next() {
		var i GetSpendingPaceRow
		if err := rows.Scan(&i.DayOfMonth, &i.CumulativeSpending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyTrend = `-- name: MonthlyTrend :many
SELECT
    DATE_TRUNC('month', date)::DATE as month,
    ABS(SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END))::BIGINT as total_spending,
    SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END)::BIGINT as total_income,
    COUNT(*)::INTEGER as transaction_count
FROM kanjo.transactions
WHERE date >= $1 AND date <= $2
    AND is_transfer = FALSE
GROUP BY DATE_TRUNC('month', date)
ORDER BY month
`

type MonthlyTrendParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type MonthlyTrendRow struct {
	Month            pgtype.Date `json:"month"`
	TotalSpending    int64       `json:"total_spending"`
	TotalIncome      int64       `json:"total_income"`
	TransactionCount int32       `json:"transaction_count"`
}

func (q *Queries) MonthlyTrend(ctx context.Context, arg MonthlyTrendParams) ([]MonthlyTrendRow, error) {
	rows, err := q.db.Query(ctx, monthlyTrend, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyTrendRow{}
	for rows.Next() {
		var i MonthlyTrendRow
		if err := rows.Scan(
			&i.Month,
			&i.TotalSpending,
			&i.TotalIncome,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendingByCategory = `-- name: SpendingByCategory :many
SELECT
    c.id as category_id,
    c.display_name as category_name,
    c.icon as category_icon,
    c.color as category_color,
    ABS(SUM(t.amount))::BIGINT as total_amount,
    COUNT(*)::INTEGER as transaction_count
FROM kanjo.transactions t
JOIN kanjo.categories c ON t.category_id = c.id
WHERE t.date >= $1 AND t.date <= $2
    AND t.amount < 0
    AND t.is_transfer = FALSE
GROUP BY c.id, c.display_name, c.icon, c.color
ORDER BY total_amount DESC
`

type SpendingByCategoryParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type SpendingByCategoryRow struct {
	CategoryID       string `json:"category_id"`
	CategoryName     string `json:"category_name"`
	CategoryIcon     string `json:"category_icon"`
	CategoryColor    string `json:"category_color"`
	TotalAmount      int64  `json:"total_amount"`
	TransactionCount int32  `json:"transaction_count"`
}

func (q *Queries) SpendingByCategory(ctx context.Context, arg SpendingByCategoryParams) ([]SpendingByCategoryRow, error) {
	rows, err := q.db.Query(ctx, spendingByCategory, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendingByCategoryRow{}
	for rows.Next() {
		var i SpendingByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
