// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBudgetCategory = `-- name: DeleteBudgetCategory :exec
DELETE FROM kanjo.budget_categories
WHERE category_name = $1
`

func (q *Queries) DeleteBudgetCategory(ctx context.Context, categoryName string) error {
	_, err := q.db.Exec(ctx, deleteBudgetCategory, categoryName)
	return err
}

const getBudgetCategory = `-- name: GetBudgetCategory :one
SELECT category_name, monthly_budget, rollover_enabled, color, created_at, updated_at FROM kanjo.budget_categories
WHERE category_name = $1
`

func (q *Queries) GetBudgetCategory(ctx context.Context, categoryName string) (KanjoBudgetCategory, error) {
	row := q.db.QueryRow(ctx, getBudgetCategory, categoryName)
	var i KanjoBudgetCategory
	err := row.Scan(
		&i.CategoryName,
		&i.MonthlyBudget,
		&i.RolloverEnabled,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetPeriod = `-- name: GetBudgetPeriod :one
SELECT id, category_name, period, budget, rollover, spent, created_at, updated_at FROM kanjo.budget_periods
WHERE category_name = $1 AND period = $2
`

type GetBudgetPeriodParams struct {
	CategoryName string      `json:"category_name"`
	Period       pgtype.Date `json:"period"`
}

func (q *Queries) GetBudgetPeriod(ctx context.Context, arg GetBudgetPeriodParams) (KanjoBudgetPeriod, error) {
	row := q.db.QueryRow(ctx, getBudgetPeriod, arg.CategoryName, arg.Period)
	var i KanjoBudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.Period,
		&i.Budget,
		&i.Rollover,
		&i.Spent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgetCategories = `-- name: ListBudgetCategories :many
SELECT category_name, monthly_budget, rollover_enabled, color, created_at, updated_at FROM kanjo.budget_categories
ORDER BY category_name
`

func (q *Queries) ListBudgetCategories(ctx context.Context) ([]KanjoBudgetCategory, error) {
	rows, err := q.db.Query(ctx, listBudgetCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanjoBudgetCategory{}
	for rows.Next() {
		var i KanjoBudgetCategory
		if err := rows.Scan(
			&i.CategoryName,
			&i.MonthlyBudget,
			&i.RolloverEnabled,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetPeriods = `-- name: ListBudgetPeriods :many
SELECT id, category_name, period, budget, rollover, spent, created_at, updated_at FROM kanjo.budget_periods
WHERE category_name = $1
ORDER BY period DESC
LIMIT $2
`

type ListBudgetPeriodsParams struct {
	CategoryName string `json:"category_name"`
	Limit        int32  `json:"limit"`
}

func (q *Queries) ListBudgetPeriods(ctx context.Context, arg ListBudgetPeriodsParams) ([]KanjoBudgetPeriod, error) {
	rows, err := q.db.Query(ctx, listBudgetPeriods, arg.CategoryName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanjoBudgetPeriod{}
	for rows.Next() {
		var i KanjoBudgetPeriod
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.Period,
			&i.Budget,
			&i.Rollover,
			&i.Spent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudgetCategory = `-- name: UpsertBudgetCategory :exec
INSERT INTO kanjo.budget_categories (category_name, monthly_budget, rollover_enabled, color, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (category_name) DO UPDATE SET
    monthly_budget = EXCLUDED.monthly_budget,
    rollover_enabled = EXCLUDED.rollover_enabled,
    color = EXCLUDED.color,
    updated_at = NOW()
`

type UpsertBudgetCategoryParams struct {
	CategoryName    string `json:"category_name"`
	MonthlyBudget   int64  `json:"monthly_budget"`
	RolloverEnabled bool   `json:"rollover_enabled"`
	Color           string `json:"color"`
}

func (q *Queries) UpsertBudgetCategory(ctx context.Context, arg UpsertBudgetCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertBudgetCategory,
		arg.CategoryName,
		arg.MonthlyBudget,
		arg.RolloverEnabled,
		arg.Color,
	)
	return err
}

const upsertBudgetPeriod = `-- name: UpsertBudgetPeriod :exec
INSERT INTO kanjo.budget_periods (category_name, period, budget, rollover, spent, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (category_name, period) DO UPDATE SET
    budget = EXCLUDED.budget,
    rollover = EXCLUDED.rollover,
    spent = EXCLUDED.spent,
    updated_at = NOW()
`

type UpsertBudgetPeriodParams struct {
	CategoryName string      `json:"category_name"`
	Period       pgtype.Date `json:"period"`
	Budget       int64       `json:"budget"`
	Rollover     int64       `json:"rollover"`
	Spent        int64       `json:"spent"`
}

func (q *Queries) UpsertBudgetPeriod(ctx context.Context, arg UpsertBudgetPeriodParams) error {
	_, err := q.db.Exec(ctx, upsertBudgetPeriod,
		arg.CategoryName,
		arg.Period,
		arg.Budget,
		arg.Rollover,
		arg.Spent,
	)
	return err
}
