// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO kanjo.chat_messages (conversation_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, role, content, created_at
`

type CreateChatMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (KanjoChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage, arg.ConversationID, arg.Role, arg.Content)
	var i KanjoChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO kanjo.chat_conversations (title, model)
VALUES ($1, $2)
RETURNING id, title, model, created_at, updated_at
`

type CreateConversationParams struct {
	Title string `json:"title"`
	Model string `json:"model"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (KanjoChatConversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Title, arg.Model)
	var i KanjoChatConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM kanjo.chat_conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, title, model, created_at, updated_at FROM kanjo.chat_conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (KanjoChatConversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i KanjoChatConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, conversation_id, role, content, created_at FROM kanjo.chat_messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListChatMessages(ctx context.Context, conversationID pgtype.UUID) ([]KanjoChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanjoChatMessage{}
	for rows.Next() {
		var i KanjoChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, title, model, created_at, updated_at FROM kanjo.chat_conversations
ORDER BY updated_at DESC
LIMIT $1
`

func (q *Queries) ListConversations(ctx context.Context, limit int32) ([]KanjoChatConversation, error) {
	rows, err := q.db.Query(ctx, listConversations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanjoChatConversation{}
	for rows.Next() {
		var i KanjoChatConversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE kanjo.chat_conversations
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}
