// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveGoal = `-- name: ArchiveGoal :exec
UPDATE kanjo.savings_goals
SET archived = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchiveGoal(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, archiveGoal, id)
	return err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO kanjo.savings_goals (name, target_amount, current_amount, deadline, icon, color)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, target_amount, current_amount, deadline, icon, color, archived, created_at, updated_at
`

type CreateGoalParams struct {
	Name          string      `json:"name"`
	TargetAmount  int64       `json:"target_amount"`
	CurrentAmount int64       `json:"current_amount"`
	Deadline      pgtype.Date `json:"deadline"`
	Icon          string      `json:"icon"`
	Color         string      `json:"color"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (KanjoSavingsGoal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.Name,
		arg.TargetAmount,
		arg.CurrentAmount,
		arg.Deadline,
		arg.Icon,
		arg.Color,
	)
	var i KanjoSavingsGoal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Icon,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM kanjo.savings_goals
WHERE id = $1
`

func (q *Queries) DeleteGoal(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGoal, id)
	return err
}

const getGoal = `-- name: GetGoal :one
SELECT id, name, target_amount, current_amount, deadline, icon, color, archived, created_at, updated_at FROM kanjo.savings_goals
WHERE id = $1
`

func (q *Queries) GetGoal(ctx context.Context, id int64) (KanjoSavingsGoal, error) {
	row := q.db.QueryRow(ctx, getGoal, id)
	var i KanjoSavingsGoal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Icon,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllGoals = `-- name: ListAllGoals :many
SELECT id, name, target_amount, current_amount, deadline, icon, color, archived, created_at, updated_at FROM kanjo.savings_goals
ORDER BY archived, deadline NULLS LAST, created_at DESC
`

func (q *Queries) ListAllGoals(ctx context.Context) ([]KanjoSavingsGoal, error) {
	rows, err := q.db.Query(ctx, listAllGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanjoSavingsGoal{}
	for rows.Next() {
		var i KanjoSavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.Deadline,
			&i.Icon,
			&i.Color,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, name, target_amount, current_amount, deadline, icon, color, archived, created_at, updated_at FROM kanjo.savings_goals
WHERE archived = FALSE
ORDER BY deadline NULLS LAST, created_at DESC
`

func (q *Queries) ListGoals(ctx context.Context) ([]KanjoSavingsGoal, error) {
	rows, err := q.db.Query(ctx, listGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanjoSavingsGoal{}
	for rows.Next() {
		var i KanjoSavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.Deadline,
			&i.Icon,
			&i.Color,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :exec
UPDATE kanjo.savings_goals
SET
    name = COALESCE($2, name),
    target_amount = COALESCE($3, target_amount),
    current_amount = COALESCE($4, current_amount),
    deadline = COALESCE($5, deadline),
    icon = COALESCE($6, icon),
    color = COALESCE($7, color),
    archived = COALESCE($8, archived),
    updated_at = NOW()
WHERE id = $1
`

type UpdateGoalParams struct {
	ID            int64       `json:"id"`
	Name          pgtype.Text `json:"name"`
	TargetAmount  pgtype.Int8 `json:"target_amount"`
	CurrentAmount pgtype.Int8 `json:"current_amount"`
	Deadline      pgtype.Date `json:"deadline"`
	Icon          pgtype.Text `json:"icon"`
	Color         pgtype.Text `json:"color"`
	Archived      pgtype.Bool `json:"archived"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) error {
	_, err := q.db.Exec(ctx, updateGoal,
		arg.ID,
		arg.Name,
		arg.TargetAmount,
		arg.CurrentAmount,
		arg.Deadline,
		arg.Icon,
		arg.Color,
		arg.Archived,
	)
	return err
}
