// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insights.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInsight = `-- name: CreateInsight :one
INSERT INTO kanjo.insights (type, title, description, action_url, expires_at, dedup_key)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (dedup_key) WHERE dedup_key IS NOT NULL DO NOTHING
RETURNING id, type, title, description, action_url, dismissed, expires_at, created_at, dedup_key
`

type CreateInsightParams struct {
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	ActionUrl   pgtype.Text        `json:"action_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	DedupKey    pgtype.Text        `json:"dedup_key"`
}

func (q *Queries) CreateInsight(ctx context.Context, arg CreateInsightParams) (KanjoInsight, error) {
	row := q.db.QueryRow(ctx, createInsight,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.ActionUrl,
		arg.ExpiresAt,
		arg.DedupKey,
	)
	var i KanjoInsight
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.ActionUrl,
		&i.Dismissed,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DedupKey,
	)
	return i, err
}

const deleteExpiredInsights = `-- name: DeleteExpiredInsights :exec
DELETE FROM kanjo.insights
WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredInsights(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredInsights)
	return err
}

const dismissInsight = `-- name: DismissInsight :exec
UPDATE kanjo.insights
SET dismissed = TRUE
WHERE id = $1
`

func (q *Queries) DismissInsight(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, dismissInsight, id)
	return err
}

const getInsight = `-- name: GetInsight :one
SELECT id, type, title, description, action_url, dismissed, expires_at, created_at, dedup_key FROM kanjo.insights
WHERE id = $1
`

func (q *Queries) GetInsight(ctx context.Context, id int64) (KanjoInsight, error) {
	row := q.db.QueryRow(ctx, getInsight, id)
	var i KanjoInsight
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.ActionUrl,
		&i.Dismissed,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DedupKey,
	)
	return i, err
}

const listInsights = `-- name: ListInsights :many
SELECT id, type, title, description, action_url, dismissed, expires_at, created_at, dedup_key FROM kanjo.insights
WHERE
    dismissed = FALSE
    AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListInsights(ctx context.Context, limit int32) ([]KanjoInsight, error) {
	rows, err := q.db.Query(ctx, listInsights, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanjoInsight{}
	for rows.Next() {
		var i KanjoInsight
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.ActionUrl,
			&i.Dismissed,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.DedupKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
