// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: institutions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInstitution = `-- name: GetInstitution :one
SELECT
    institution_name,
    COALESCE(display_name, institution_name) as display_name,
    icon,
    COALESCE(color, '#6B7280') as color,
    hidden
FROM kanjo.institutions
WHERE institution_name = $1
`

type GetInstitutionRow struct {
	InstitutionName string      `json:"institution_name"`
	DisplayName     string      `json:"display_name"`
	Icon            pgtype.Text `json:"icon"`
	Color           string      `json:"color"`
	Hidden          bool        `json:"hidden"`
}

func (q *Queries) GetInstitution(ctx context.Context, institutionName string) (GetInstitutionRow, error) {
	row := q.db.QueryRow(ctx, getInstitution, institutionName)
	var i GetInstitutionRow
	err := row.Scan(
		&i.InstitutionName,
		&i.DisplayName,
		&i.Icon,
		&i.Color,
		&i.Hidden,
	)
	return i, err
}

const listInstitutions = `-- name: ListInstitutions :many
SELECT
    institution_name,
    COALESCE(display_name, institution_name) as display_name,
    icon,
    COALESCE(color, '#6B7280') as color,
    hidden
FROM kanjo.institutions
ORDER BY institution_name
`

type ListInstitutionsRow struct {
	InstitutionName string      `json:"institution_name"`
	DisplayName     string      `json:"display_name"`
	Icon            pgtype.Text `json:"icon"`
	Color           string      `json:"color"`
	Hidden          bool        `json:"hidden"`
}

func (q *Queries) ListInstitutions(ctx context.Context) ([]ListInstitutionsRow, error) {
	rows, err := q.db.Query(ctx, listInstitutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstitutionsRow{}
	for rows.Next() {
		var i ListInstitutionsRow
		if err := rows.Scan(
			&i.InstitutionName,
			&i.DisplayName,
			&i.Icon,
			&i.Color,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInstitution = `-- name: UpsertInstitution :exec
INSERT INTO kanjo.institutions (institution_name, display_name, icon, color, hidden, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (institution_name) DO UPDATE SET
    display_name = COALESCE(EXCLUDED.display_name, kanjo.institutions.display_name),
    icon = COALESCE(EXCLUDED.icon, kanjo.institutions.icon),
    color = COALESCE(EXCLUDED.color, kanjo.institutions.color),
    hidden = COALESCE(EXCLUDED.hidden, kanjo.institutions.hidden),
    updated_at = NOW()
`

type UpsertInstitutionParams struct {
	InstitutionName string      `json:"institution_name"`
	DisplayName     pgtype.Text `json:"display_name"`
	Icon            pgtype.Text `json:"icon"`
	Color           pgtype.Text `json:"color"`
	Hidden          bool        `json:"hidden"`
}

func (q *Queries) UpsertInstitution(ctx context.Context, arg UpsertInstitutionParams) error {
	_, err := q.db.Exec(ctx, upsertInstitution,
		arg.InstitutionName,
		arg.DisplayName,
		arg.Icon,
		arg.Color,
		arg.Hidden,
	)
	return err
}
