// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyAsset struct {
	ID              int64              `json:"id"`
	Date            pgtype.Date        `json:"date"`
	InstitutionName string             `json:"institution_name"`
	AccountName     string             `json:"account_name"`
	AssetType       string             `json:"asset_type"`
	Balance         int64              `json:"balance"`
	Currency        string             `json:"currency"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type JobRun struct {
	ID                   int64              `json:"id"`
	JobType              string             `json:"job_type"`
	Status               string             `json:"status"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	TransactionsImported pgtype.Int4        `json:"transactions_imported"`
	AssetsImported       pgtype.Int4        `json:"assets_imported"`
}

type KanjoAppSetting struct {
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	IsSecret    bool               `json:"is_secret"`
	Description string             `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type KanjoBudgetCategory struct {
	CategoryName    string             `json:"category_name"`
	MonthlyBudget   int64              `json:"monthly_budget"`
	RolloverEnabled bool               `json:"rollover_enabled"`
	Color           string             `json:"color"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type KanjoBudgetPeriod struct {
	ID           int64              `json:"id"`
	CategoryName string             `json:"category_name"`
	Period       pgtype.Date        `json:"period"`
	Budget       int64              `json:"budget"`
	Rollover     int64              `json:"rollover"`
	Spent        int64              `json:"spent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type KanjoCategory struct {
	ID          string             `json:"id"`
	MfCategory  string             `json:"mf_category"`
	DisplayName string             `json:"display_name"`
	Icon        string             `json:"icon"`
	Color       string             `json:"color"`
	IsIncome    bool               `json:"is_income"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type KanjoChatConversation struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Model     string             `json:"model"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type KanjoChatMessage struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type KanjoDailyAsset struct {
	ID              pgtype.UUID        `json:"id"`
	RawID           pgtype.UUID        `json:"raw_id"`
	Date            pgtype.Date        `json:"date"`
	InstitutionName string             `json:"institution_name"`
	AccountName     string             `json:"account_name"`
	AssetType       string             `json:"asset_type"`
	Balance         int64              `json:"balance"`
	TransformedAt   pgtype.Timestamptz `json:"transformed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type KanjoInsight struct {
	ID          int64              `json:"id"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	ActionUrl   pgtype.Text        `json:"action_url"`
	Dismissed   bool               `json:"dismissed"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DedupKey    pgtype.Text        `json:"dedup_key"`
}

type KanjoInstitution struct {
	InstitutionName string             `json:"institution_name"`
	DisplayName     pgtype.Text        `json:"display_name"`
	Icon            pgtype.Text        `json:"icon"`
	Color           pgtype.Text        `json:"color"`
	Hidden          bool               `json:"hidden"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type KanjoMerchant struct {
	ID             pgtype.UUID        `json:"id"`
	RawDescription string             `json:"raw_description"`
	NormalizedName string             `json:"normalized_name"`
	DisplayName    pgtype.Text        `json:"display_name"`
	Icon           pgtype.Text        `json:"icon"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type KanjoRecurringPattern struct {
	ID                 pgtype.UUID        `json:"id"`
	MerchantID         pgtype.UUID        `json:"merchant_id"`
	CategoryID         pgtype.Text        `json:"category_id"`
	DescriptionPattern string             `json:"description_pattern"`
	AmountMin          pgtype.Int8        `json:"amount_min"`
	AmountMax          pgtype.Int8        `json:"amount_max"`
	Frequency          string             `json:"frequency"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type KanjoSavingsGoal struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	TargetAmount  int64              `json:"target_amount"`
	CurrentAmount int64              `json:"current_amount"`
	Deadline      pgtype.Date        `json:"deadline"`
	Icon          string             `json:"icon"`
	Color         string             `json:"color"`
	Archived      bool               `json:"archived"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type KanjoTransaction struct {
	Hash               string             `json:"hash"`
	RawHash            string             `json:"raw_hash"`
	Date               pgtype.Date        `json:"date"`
	Amount             int64              `json:"amount"`
	AccountName        string             `json:"account_name"`
	Description        string             `json:"description"`
	MerchantID         pgtype.UUID        `json:"merchant_id"`
	CategoryID         pgtype.Text        `json:"category_id"`
	IsTransfer         bool               `json:"is_transfer"`
	IsRecurring        bool               `json:"is_recurring"`
	TransferPairHash   pgtype.Text        `json:"transfer_pair_hash"`
	Reviewed           bool               `json:"reviewed"`
	Tags               []string           `json:"tags"`
	CategoryOverride   pgtype.Text        `json:"category_override"`
	Notes              pgtype.Text        `json:"notes"`
	CategoryConfidence pgtype.Int4        `json:"category_confidence"`
	MerchantConfidence pgtype.Int4        `json:"merchant_confidence"`
	TransformedAt      pgtype.Timestamptz `json:"transformed_at"`
	TransformVersion   int32              `json:"transform_version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type KanjoTransferPair struct {
	ID           pgtype.UUID        `json:"id"`
	FromHash     string             `json:"from_hash"`
	ToHash       string             `json:"to_hash"`
	Confidence   int32              `json:"confidence"`
	AutoDetected bool               `json:"auto_detected"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type KanjoTransformRun struct {
	ID                      pgtype.UUID        `json:"id"`
	TriggerJobRunID         pgtype.UUID        `json:"trigger_job_run_id"`
	Status                  string             `json:"status"`
	StartedAt               pgtype.Timestamptz `json:"started_at"`
	CompletedAt             pgtype.Timestamptz `json:"completed_at"`
	TransactionsProcessed   pgtype.Int4        `json:"transactions_processed"`
	TransactionsTransformed pgtype.Int4        `json:"transactions_transformed"`
	MerchantsCreated        pgtype.Int4        `json:"merchants_created"`
	TransfersMatched        pgtype.Int4        `json:"transfers_matched"`
	LlmCallsMade            pgtype.Int4        `json:"llm_calls_made"`
	Error                   pgtype.Text        `json:"error"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type MfRawDailyAsset struct {
	ID              pgtype.UUID        `json:"id"`
	Date            pgtype.Date        `json:"date"`
	InstitutionName string             `json:"institution_name"`
	AccountName     string             `json:"account_name"`
	AssetType       string             `json:"asset_type"`
	Balance         int64              `json:"balance"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MfRawJobRun struct {
	ID                pgtype.UUID        `json:"id"`
	JobType           string             `json:"job_type"`
	Status            string             `json:"status"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	Error             pgtype.Text        `json:"error"`
	TransactionsCount pgtype.Int4        `json:"transactions_count"`
	AssetsCount       pgtype.Int4        `json:"assets_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MfRawMfSession struct {
	ID           pgtype.UUID        `json:"id"`
	StorageState []byte             `json:"storage_state"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type MfRawTransaction struct {
	Hash        string             `json:"hash"`
	Date        pgtype.Date        `json:"date"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Category    string             `json:"category"`
	SubCategory pgtype.Text        `json:"sub_category"`
	AccountName string             `json:"account_name"`
	Memo        pgtype.Text        `json:"memo"`
	IsTransfer  bool               `json:"is_transfer"`
	IsRecurring bool               `json:"is_recurring"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	Hash        string             `json:"hash"`
	Date        pgtype.Date        `json:"date"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Category    string             `json:"category"`
	SubCategory pgtype.Text        `json:"sub_category"`
	AccountName string             `json:"account_name"`
	Memo        pgtype.Text        `json:"memo"`
	IsTransfer  bool               `json:"is_transfer"`
	IsRecurring bool               `json:"is_recurring"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
