// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package repository

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, is_secret, description, updated_at FROM kanjo.app_settings
WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (KanjoAppSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i KanjoAppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, is_secret, description, updated_at FROM kanjo.app_settings
ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]KanjoAppSetting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanjoAppSetting{}
	for rows.Next() {
		var i KanjoAppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO kanjo.app_settings (key, value, is_secret, description, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
`

type UpsertSettingParams struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	IsSecret    bool   `json:"is_secret"`
	Description string `json:"description"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.Description,
	)
	return err
}
