// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastSyncStatus = `-- name: GetLastSyncStatus :one
SELECT id, status, completed_at, transactions_processed, transactions_transformed
FROM kanjo.transform_runs
WHERE status = 'completed'
ORDER BY completed_at DESC
LIMIT 1
`

type GetLastSyncStatusRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Status                  string             `json:"status"`
	CompletedAt             pgtype.Timestamptz `json:"completed_at"`
	TransactionsProcessed   pgtype.Int4        `json:"transactions_processed"`
	TransactionsTransformed pgtype.Int4        `json:"transactions_transformed"`
}

func (q *Queries) GetLastSyncStatus(ctx context.Context) (GetLastSyncStatusRow, error) {
	row := q.db.QueryRow(ctx, getLastSyncStatus)
	var i GetLastSyncStatusRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CompletedAt,
		&i.TransactionsProcessed,
		&i.TransactionsTransformed,
	)
	return i, err
}
