// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*)
FROM kanjo.transactions t
WHERE
    ($1::TEXT IS NULL OR t.description ILIKE '%' || $1 || '%')
    AND ($2::TEXT[] IS NULL OR t.category_id = ANY($2))
    AND ($3::DATE IS NULL OR t.date >= $3)
    AND ($4::DATE IS NULL OR t.date <= $4)
    AND ($5::BOOLEAN IS NULL OR t.reviewed = $5)
`

type CountTransactionsParams struct {
	Column1  string      `json:"column_1"`
	Column2  []string    `json:"column_2"`
	Column3  pgtype.Date `json:"column_3"`
	Column4  pgtype.Date `json:"column_4"`
	Reviewed pgtype.Bool `json:"reviewed"`
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Reviewed,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentTransactions = `-- name: GetRecentTransactions :many
SELECT
    t.hash,
    t.date,
    t.description,
    t.amount,
    c.display_name as category_name,
    t.account_name,
    t.reviewed
FROM kanjo.transactions t
LEFT JOIN kanjo.categories c ON t.category_id = c.id
ORDER BY t.date DESC, t.created_at DESC
LIMIT $1
`

type GetRecentTransactionsRow struct {
	Hash         string      `json:"hash"`
	Date         pgtype.Date `json:"date"`
	Description  string      `json:"description"`
	Amount       int64       `json:"amount"`
	CategoryName pgtype.Text `json:"category_name"`
	AccountName  string      `json:"account_name"`
	Reviewed     bool        `json:"reviewed"`
}

func (q *Queries) GetRecentTransactions(ctx context.Context, limit int32) ([]GetRecentTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getRecentTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentTransactionsRow{}
	for rows.Next() {
		var i GetRecentTransactionsRow
		if err := rows.Scan(
			&i.Hash,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.CategoryName,
			&i.AccountName,
			&i.Reviewed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByHash = `-- name: GetTransactionByHash :one
SELECT
    t.hash,
    t.raw_hash,
    t.date,
    t.description,
    t.amount,
    c.id as category_id,
    c.display_name as category_name,
    c.icon as category_icon,
    c.color as category_color,
    m.normalized_name as merchant_name,
    m.display_name as merchant_display_name,
    m.icon as merchant_icon,
    t.account_name,
    t.is_transfer,
    t.is_recurring,
    t.reviewed,
    t.tags,
    t.category_override,
    t.notes,
    t.category_confidence,
    t.created_at
FROM kanjo.transactions t
LEFT JOIN kanjo.categories c ON t.category_id = c.id
LEFT JOIN kanjo.merchants m ON t.merchant_id = m.id
WHERE t.hash = $1
`

type GetTransactionByHashRow struct {
	Hash                string             `json:"hash"`
	RawHash             string             `json:"raw_hash"`
	Date                pgtype.Date        `json:"date"`
	Description         string             `json:"description"`
	Amount              int64              `json:"amount"`
	CategoryID          pgtype.Text        `json:"category_id"`
	CategoryName        pgtype.Text        `json:"category_name"`
	CategoryIcon        pgtype.Text        `json:"category_icon"`
	CategoryColor       pgtype.Text        `json:"category_color"`
	MerchantName        pgtype.Text        `json:"merchant_name"`
	MerchantDisplayName pgtype.Text        `json:"merchant_display_name"`
	MerchantIcon        pgtype.Text        `json:"merchant_icon"`
	AccountName         string             `json:"account_name"`
	IsTransfer          bool               `json:"is_transfer"`
	IsRecurring         bool               `json:"is_recurring"`
	Reviewed            bool               `json:"reviewed"`
	Tags                []string           `json:"tags"`
	CategoryOverride    pgtype.Text        `json:"category_override"`
	Notes               pgtype.Text        `json:"notes"`
	CategoryConfidence  pgtype.Int4        `json:"category_confidence"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetTransactionByHash(ctx context.Context, hash string) (GetTransactionByHashRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByHash, hash)
	var i GetTransactionByHashRow
	err := row.Scan(
		&i.Hash,
		&i.RawHash,
		&i.Date,
		&i.Description,
		&i.Amount,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.CategoryColor,
		&i.MerchantName,
		&i.MerchantDisplayName,
		&i.MerchantIcon,
		&i.AccountName,
		&i.IsTransfer,
		&i.IsRecurring,
		&i.Reviewed,
		&i.Tags,
		&i.CategoryOverride,
		&i.Notes,
		&i.CategoryConfidence,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, mf_category, display_name, icon, color, is_income, sort_order
FROM kanjo.categories
ORDER BY sort_order, display_name
`

type ListCategoriesRow struct {
	ID          string `json:"id"`
	MfCategory  string `json:"mf_category"`
	DisplayName string `json:"display_name"`
	Icon        string `json:"icon"`
	Color       string `json:"color"`
	IsIncome    bool   `json:"is_income"`
	SortOrder   int32  `json:"sort_order"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.MfCategory,
			&i.DisplayName,
			&i.Icon,
			&i.Color,
			&i.IsIncome,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.hash,
    t.raw_hash,
    t.date,
    t.description,
    t.amount,
    c.id as category_id,
    c.display_name as category_name,
    c.icon as category_icon,
    c.color as category_color,
    m.normalized_name as merchant_name,
    m.display_name as merchant_display_name,
    m.icon as merchant_icon,
    t.account_name,
    t.is_transfer,
    t.is_recurring,
    t.reviewed,
    t.tags,
    t.category_override,
    t.notes,
    t.category_confidence,
    t.created_at
FROM kanjo.transactions t
LEFT JOIN kanjo.categories c ON t.category_id = c.id
LEFT JOIN kanjo.merchants m ON t.merchant_id = m.id
WHERE
    ($3::TEXT IS NULL OR t.description ILIKE '%' || $3 || '%')
    AND ($4::TEXT[] IS NULL OR t.category_id = ANY($4))
    AND ($5::DATE IS NULL OR t.date >= $5)
    AND ($6::DATE IS NULL OR t.date <= $6)
    AND ($7::BOOLEAN IS NULL OR t.reviewed = $7)
ORDER BY t.date DESC, t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Column3  string      `json:"column_3"`
	Column4  []string    `json:"column_4"`
	Column5  pgtype.Date `json:"column_5"`
	Column6  pgtype.Date `json:"column_6"`
	Reviewed pgtype.Bool `json:"reviewed"`
}

type ListTransactionsRow struct {
	Hash                string             `json:"hash"`
	RawHash             string             `json:"raw_hash"`
	Date                pgtype.Date        `json:"date"`
	Description         string             `json:"description"`
	Amount              int64              `json:"amount"`
	CategoryID          pgtype.Text        `json:"category_id"`
	CategoryName        pgtype.Text        `json:"category_name"`
	CategoryIcon        pgtype.Text        `json:"category_icon"`
	CategoryColor       pgtype.Text        `json:"category_color"`
	MerchantName        pgtype.Text        `json:"merchant_name"`
	MerchantDisplayName pgtype.Text        `json:"merchant_display_name"`
	MerchantIcon        pgtype.Text        `json:"merchant_icon"`
	AccountName         string             `json:"account_name"`
	IsTransfer          bool               `json:"is_transfer"`
	IsRecurring         bool               `json:"is_recurring"`
	Reviewed            bool               `json:"reviewed"`
	Tags                []string           `json:"tags"`
	CategoryOverride    pgtype.Text        `json:"category_override"`
	Notes               pgtype.Text        `json:"notes"`
	CategoryConfidence  pgtype.Int4        `json:"category_confidence"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Reviewed,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.Hash,
			&i.RawHash,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.MerchantName,
			&i.MerchantDisplayName,
			&i.MerchantIcon,
			&i.AccountName,
			&i.IsTransfer,
			&i.IsRecurring,
			&i.Reviewed,
			&i.Tags,
			&i.CategoryOverride,
			&i.Notes,
			&i.CategoryConfidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionMetadata = `-- name: UpdateTransactionMetadata :exec
UPDATE kanjo.transactions
SET
    reviewed = $2,
    tags = $3,
    category_override = $4,
    notes = $5,
    updated_at = NOW()
WHERE hash = $1
`

type UpdateTransactionMetadataParams struct {
	Hash             string      `json:"hash"`
	Reviewed         bool        `json:"reviewed"`
	Tags             []string    `json:"tags"`
	CategoryOverride pgtype.Text `json:"category_override"`
	Notes            pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateTransactionMetadata(ctx context.Context, arg UpdateTransactionMetadataParams) error {
	_, err := q.db.Exec(ctx, updateTransactionMetadata,
		arg.Hash,
		arg.Reviewed,
		arg.Tags,
		arg.CategoryOverride,
		arg.Notes,
	)
	return err
}
